// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: jaeger.proto

/*
	Package model is a generated protocol buffer package.

	It is generated from these files:
		jaeger.proto

	It has these top-level messages:
		TraceID
		KeyValue
		Log
		SpanRef
		Process
		Span
		Span2
		Trace
		Batch
		GetTraceID
*/
package model

import proto "github.com/gogo/protobuf/proto"
import golang_proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/gogo/protobuf/gogoproto"

import time "time"

import bytes "bytes"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import binary "encoding/binary"
import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_STRING  ValueType = 0
	ValueType_BOOL    ValueType = 1
	ValueType_INT64   ValueType = 2
	ValueType_FLOAT64 ValueType = 3
	ValueType_BINARY  ValueType = 4
)

var ValueType_name = map[int32]string{
	0: "STRING",
	1: "BOOL",
	2: "INT64",
	3: "FLOAT64",
	4: "BINARY",
}
var ValueType_value = map[string]int32{
	"STRING":  0,
	"BOOL":    1,
	"INT64":   2,
	"FLOAT64": 3,
	"BINARY":  4,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{0} }

type SpanRefType int32

const (
	SpanRefType_CHILD_OF     SpanRefType = 0
	SpanRefType_FOLLOWS_FROM SpanRefType = 1
)

var SpanRefType_name = map[int32]string{
	0: "CHILD_OF",
	1: "FOLLOWS_FROM",
}
var SpanRefType_value = map[string]int32{
	"CHILD_OF":     0,
	"FOLLOWS_FROM": 1,
}

func (x SpanRefType) String() string {
	return proto.EnumName(SpanRefType_name, int32(x))
}
func (SpanRefType) EnumDescriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{1} }

type TraceID struct {
	Low  uint64 `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High uint64 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
}

func (m *TraceID) Reset()                    { *m = TraceID{} }
func (*TraceID) ProtoMessage()               {}
func (*TraceID) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{0} }

func (m *TraceID) GetLow() uint64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *TraceID) GetHigh() uint64 {
	if m != nil {
		return m.High
	}
	return 0
}

type KeyValue struct {
	Key      string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	VType    ValueType `protobuf:"varint,2,opt,name=vType,proto3,enum=jaeger.ValueType" json:"vType,omitempty"`
	VStr     string    `protobuf:"bytes,3,opt,name=vStr,proto3" json:"vStr,omitempty"`
	VBool    bool      `protobuf:"varint,4,opt,name=vBool,proto3" json:"vBool,omitempty"`
	VInt64   int64     `protobuf:"varint,5,opt,name=vInt64,proto3" json:"vInt64,omitempty"`
	VFloat64 float64   `protobuf:"fixed64,6,opt,name=vFloat64,proto3" json:"vFloat64,omitempty"`
	VBinary  []byte    `protobuf:"bytes,7,opt,name=vBinary,proto3" json:"vBinary,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{1} }

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetVType() ValueType {
	if m != nil {
		return m.VType
	}
	return ValueType_STRING
}

func (m *KeyValue) GetVStr() string {
	if m != nil {
		return m.VStr
	}
	return ""
}

func (m *KeyValue) GetVBool() bool {
	if m != nil {
		return m.VBool
	}
	return false
}

func (m *KeyValue) GetVInt64() int64 {
	if m != nil {
		return m.VInt64
	}
	return 0
}

func (m *KeyValue) GetVFloat64() float64 {
	if m != nil {
		return m.VFloat64
	}
	return 0
}

func (m *KeyValue) GetVBinary() []byte {
	if m != nil {
		return m.VBinary
	}
	return nil
}

type Log struct {
	Timestamp time.Time  `protobuf:"bytes,1,opt,name=timestamp,stdtime" json:"timestamp"`
	Fields    []KeyValue `protobuf:"bytes,2,rep,name=fields" json:"fields"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{2} }

func (m *Log) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *Log) GetFields() []KeyValue {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SpanRef struct {
	TraceID TraceID     `protobuf:"bytes,1,opt,name=traceID" json:"traceID"`
	SpanID  SpanID      `protobuf:"varint,2,opt,name=spanID,proto3,customtype=SpanID" json:"spanID"`
	RefType SpanRefType `protobuf:"varint,3,opt,name=refType,proto3,enum=jaeger.SpanRefType" json:"refType,omitempty"`
}

func (m *SpanRef) Reset()                    { *m = SpanRef{} }
func (m *SpanRef) String() string            { return proto.CompactTextString(m) }
func (*SpanRef) ProtoMessage()               {}
func (*SpanRef) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{3} }

func (m *SpanRef) GetTraceID() TraceID {
	if m != nil {
		return m.TraceID
	}
	return TraceID{}
}

func (m *SpanRef) GetRefType() SpanRefType {
	if m != nil {
		return m.RefType
	}
	return SpanRefType_CHILD_OF
}

type Process struct {
	ServiceName string     `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Tags        []KeyValue `protobuf:"bytes,2,rep,name=tags" json:"tags"`
}

func (m *Process) Reset()                    { *m = Process{} }
func (m *Process) String() string            { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()               {}
func (*Process) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{4} }

func (m *Process) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Process) GetTags() []KeyValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Span struct {
	TraceID       TraceID       `protobuf:"bytes,1,opt,name=traceID" json:"traceID"`
	SpanID        SpanID        `protobuf:"varint,2,opt,name=spanID,proto3,customtype=SpanID" json:"spanID"`
	OperationName string        `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	References    []SpanRef     `protobuf:"bytes,4,rep,name=references" json:"references"`
	Flags         Flags         `protobuf:"varint,5,opt,name=flags,proto3,customtype=Flags" json:"flags"`
	StartTime     time.Time     `protobuf:"bytes,6,opt,name=startTime,stdtime" json:"startTime"`
	Duration      time.Duration `protobuf:"bytes,7,opt,name=duration,stdduration" json:"duration"`
	Tags          []KeyValue    `protobuf:"bytes,8,rep,name=tags" json:"tags"`
	Logs          []Log         `protobuf:"bytes,9,rep,name=logs" json:"logs"`
	Process       *Process      `protobuf:"bytes,10,opt,name=process" json:"process,omitempty"`
	ProcessID     string        `protobuf:"bytes,11,opt,name=processID,proto3" json:"processID,omitempty"`
	Warnings      []string      `protobuf:"bytes,12,rep,name=warnings" json:"warnings,omitempty"`
}

func (m *Span) Reset()                    { *m = Span{} }
func (m *Span) String() string            { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()               {}
func (*Span) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{5} }

func (m *Span) GetTraceID() TraceID {
	if m != nil {
		return m.TraceID
	}
	return TraceID{}
}

func (m *Span) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *Span) GetReferences() []SpanRef {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *Span) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *Span) GetDuration() time.Duration {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Span) GetTags() []KeyValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Span) GetLogs() []Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *Span) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Span) GetProcessID() string {
	if m != nil {
		return m.ProcessID
	}
	return ""
}

func (m *Span) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type Span2 struct {
	TraceID TraceID `protobuf:"bytes,1,opt,name=traceID" json:"traceID"`
	SpanID  SpanID  `protobuf:"varint,2,opt,name=spanID,proto3,customtype=SpanID" json:"spanID"`
}

func (m *Span2) Reset()                    { *m = Span2{} }
func (m *Span2) String() string            { return proto.CompactTextString(m) }
func (*Span2) ProtoMessage()               {}
func (*Span2) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{6} }

func (m *Span2) GetTraceID() TraceID {
	if m != nil {
		return m.TraceID
	}
	return TraceID{}
}

type Trace struct {
	Spans      []*Span                `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
	ProcessMap []Trace_ProcessMapping `protobuf:"bytes,2,rep,name=processMap" json:"processMap"`
	Warnings   []string               `protobuf:"bytes,3,rep,name=warnings" json:"warnings,omitempty"`
}

func (m *Trace) Reset()                    { *m = Trace{} }
func (m *Trace) String() string            { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()               {}
func (*Trace) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{7} }

func (m *Trace) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *Trace) GetProcessMap() []Trace_ProcessMapping {
	if m != nil {
		return m.ProcessMap
	}
	return nil
}

func (m *Trace) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type Trace_ProcessMapping struct {
	ProcessID string  `protobuf:"bytes,1,opt,name=processID,proto3" json:"processID,omitempty"`
	Process   Process `protobuf:"bytes,2,opt,name=process" json:"process"`
}

func (m *Trace_ProcessMapping) Reset()                    { *m = Trace_ProcessMapping{} }
func (m *Trace_ProcessMapping) String() string            { return proto.CompactTextString(m) }
func (*Trace_ProcessMapping) ProtoMessage()               {}
func (*Trace_ProcessMapping) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{7, 0} }

func (m *Trace_ProcessMapping) GetProcessID() string {
	if m != nil {
		return m.ProcessID
	}
	return ""
}

func (m *Trace_ProcessMapping) GetProcess() Process {
	if m != nil {
		return m.Process
	}
	return Process{}
}

type Batch struct {
	Spans   []*Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
	Process Process `protobuf:"bytes,2,opt,name=process" json:"process"`
}

func (m *Batch) Reset()                    { *m = Batch{} }
func (m *Batch) String() string            { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()               {}
func (*Batch) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{8} }

func (m *Batch) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *Batch) GetProcess() Process {
	if m != nil {
		return m.Process
	}
	return Process{}
}

type GetTraceID struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *GetTraceID) Reset()                    { *m = GetTraceID{} }
func (m *GetTraceID) String() string            { return proto.CompactTextString(m) }
func (*GetTraceID) ProtoMessage()               {}
func (*GetTraceID) Descriptor() ([]byte, []int) { return fileDescriptorJaeger, []int{9} }

func (m *GetTraceID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*TraceID)(nil), "jaeger.TraceID")
	golang_proto.RegisterType((*TraceID)(nil), "jaeger.TraceID")
	proto.RegisterType((*KeyValue)(nil), "jaeger.KeyValue")
	golang_proto.RegisterType((*KeyValue)(nil), "jaeger.KeyValue")
	proto.RegisterType((*Log)(nil), "jaeger.Log")
	golang_proto.RegisterType((*Log)(nil), "jaeger.Log")
	proto.RegisterType((*SpanRef)(nil), "jaeger.SpanRef")
	golang_proto.RegisterType((*SpanRef)(nil), "jaeger.SpanRef")
	proto.RegisterType((*Process)(nil), "jaeger.Process")
	golang_proto.RegisterType((*Process)(nil), "jaeger.Process")
	proto.RegisterType((*Span)(nil), "jaeger.Span")
	golang_proto.RegisterType((*Span)(nil), "jaeger.Span")
	proto.RegisterType((*Span2)(nil), "jaeger.Span2")
	golang_proto.RegisterType((*Span2)(nil), "jaeger.Span2")
	proto.RegisterType((*Trace)(nil), "jaeger.Trace")
	golang_proto.RegisterType((*Trace)(nil), "jaeger.Trace")
	proto.RegisterType((*Trace_ProcessMapping)(nil), "jaeger.Trace.ProcessMapping")
	golang_proto.RegisterType((*Trace_ProcessMapping)(nil), "jaeger.Trace.ProcessMapping")
	proto.RegisterType((*Batch)(nil), "jaeger.Batch")
	golang_proto.RegisterType((*Batch)(nil), "jaeger.Batch")
	proto.RegisterType((*GetTraceID)(nil), "jaeger.GetTraceID")
	golang_proto.RegisterType((*GetTraceID)(nil), "jaeger.GetTraceID")
	proto.RegisterEnum("jaeger.ValueType", ValueType_name, ValueType_value)
	golang_proto.RegisterEnum("jaeger.ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("jaeger.SpanRefType", SpanRefType_name, SpanRefType_value)
	golang_proto.RegisterEnum("jaeger.SpanRefType", SpanRefType_name, SpanRefType_value)
}
func (this *KeyValue) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*KeyValue)
	if !ok {
		that2, ok := that.(KeyValue)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Key != that1.Key {
		if this.Key < that1.Key {
			return -1
		}
		return 1
	}
	if this.VType != that1.VType {
		if this.VType < that1.VType {
			return -1
		}
		return 1
	}
	if this.VStr != that1.VStr {
		if this.VStr < that1.VStr {
			return -1
		}
		return 1
	}
	if this.VBool != that1.VBool {
		if !this.VBool {
			return -1
		}
		return 1
	}
	if this.VInt64 != that1.VInt64 {
		if this.VInt64 < that1.VInt64 {
			return -1
		}
		return 1
	}
	if this.VFloat64 != that1.VFloat64 {
		if this.VFloat64 < that1.VFloat64 {
			return -1
		}
		return 1
	}
	if c := bytes.Compare(this.VBinary, that1.VBinary); c != 0 {
		return c
	}
	return 0
}
func (this *KeyValue) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KeyValue)
	if !ok {
		that2, ok := that.(KeyValue)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Key != that1.Key {
		return false
	}
	if this.VType != that1.VType {
		return false
	}
	if this.VStr != that1.VStr {
		return false
	}
	if this.VBool != that1.VBool {
		return false
	}
	if this.VInt64 != that1.VInt64 {
		return false
	}
	if this.VFloat64 != that1.VFloat64 {
		return false
	}
	if !bytes.Equal(this.VBinary, that1.VBinary) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CollectorServiceV1 service

type CollectorServiceV1Client interface {
	PostSpans(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type collectorServiceV1Client struct {
	cc *grpc.ClientConn
}

func NewCollectorServiceV1Client(cc *grpc.ClientConn) CollectorServiceV1Client {
	return &collectorServiceV1Client{cc}
}

func (c *collectorServiceV1Client) PostSpans(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/jaeger.CollectorServiceV1/PostSpans", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CollectorServiceV1 service

type CollectorServiceV1Server interface {
	PostSpans(context.Context, *Batch) (*google_protobuf.Empty, error)
}

func RegisterCollectorServiceV1Server(s *grpc.Server, srv CollectorServiceV1Server) {
	s.RegisterService(&_CollectorServiceV1_serviceDesc, srv)
}

func _CollectorServiceV1_PostSpans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Batch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceV1Server).PostSpans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jaeger.CollectorServiceV1/PostSpans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceV1Server).PostSpans(ctx, req.(*Batch))
	}
	return interceptor(ctx, in, info, handler)
}

var _CollectorServiceV1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jaeger.CollectorServiceV1",
	HandlerType: (*CollectorServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostSpans",
			Handler:    _CollectorServiceV1_PostSpans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jaeger.proto",
}

// Client API for QueryServiceV1 service

type QueryServiceV1Client interface {
	GetTrace(ctx context.Context, in *GetTraceID, opts ...grpc.CallOption) (*Trace, error)
}

type queryServiceV1Client struct {
	cc *grpc.ClientConn
}

func NewQueryServiceV1Client(cc *grpc.ClientConn) QueryServiceV1Client {
	return &queryServiceV1Client{cc}
}

func (c *queryServiceV1Client) GetTrace(ctx context.Context, in *GetTraceID, opts ...grpc.CallOption) (*Trace, error) {
	out := new(Trace)
	err := grpc.Invoke(ctx, "/jaeger.QueryServiceV1/GetTrace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QueryServiceV1 service

type QueryServiceV1Server interface {
	GetTrace(context.Context, *GetTraceID) (*Trace, error)
}

func RegisterQueryServiceV1Server(s *grpc.Server, srv QueryServiceV1Server) {
	s.RegisterService(&_QueryServiceV1_serviceDesc, srv)
}

func _QueryServiceV1_GetTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceV1Server).GetTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jaeger.QueryServiceV1/GetTrace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceV1Server).GetTrace(ctx, req.(*GetTraceID))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryServiceV1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jaeger.QueryServiceV1",
	HandlerType: (*QueryServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrace",
			Handler:    _QueryServiceV1_GetTrace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jaeger.proto",
}

func (m *TraceID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TraceID) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Low != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.Low))
	}
	if m.High != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.High))
	}
	return i, nil
}

func (m *KeyValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyValue) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	if m.VType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.VType))
	}
	if len(m.VStr) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.VStr)))
		i += copy(dAtA[i:], m.VStr)
	}
	if m.VBool {
		dAtA[i] = 0x20
		i++
		if m.VBool {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.VInt64 != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.VInt64))
	}
	if m.VFloat64 != 0 {
		dAtA[i] = 0x31
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.VFloat64))))
		i += 8
	}
	if len(m.VBinary) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.VBinary)))
		i += copy(dAtA[i:], m.VBinary)
	}
	return i, nil
}

func (m *Log) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Log) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(types.SizeOfStdTime(m.Timestamp)))
	n1, err := types.StdTimeMarshalTo(m.Timestamp, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if len(m.Fields) > 0 {
		for _, msg := range m.Fields {
			dAtA[i] = 0x12
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *SpanRef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpanRef) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(m.TraceID.Size()))
	n2, err := m.TraceID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if m.SpanID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.SpanID))
	}
	if m.RefType != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.RefType))
	}
	return i, nil
}

func (m *Process) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Process) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ServiceName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.ServiceName)))
		i += copy(dAtA[i:], m.ServiceName)
	}
	if len(m.Tags) > 0 {
		for _, msg := range m.Tags {
			dAtA[i] = 0x12
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Span) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Span) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(m.TraceID.Size()))
	n3, err := m.TraceID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if m.SpanID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.SpanID))
	}
	if len(m.OperationName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.OperationName)))
		i += copy(dAtA[i:], m.OperationName)
	}
	if len(m.References) > 0 {
		for _, msg := range m.References {
			dAtA[i] = 0x22
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Flags != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.Flags))
	}
	dAtA[i] = 0x32
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(types.SizeOfStdTime(m.StartTime)))
	n4, err := types.StdTimeMarshalTo(m.StartTime, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	dAtA[i] = 0x3a
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(types.SizeOfStdDuration(m.Duration)))
	n5, err := types.StdDurationMarshalTo(m.Duration, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	if len(m.Tags) > 0 {
		for _, msg := range m.Tags {
			dAtA[i] = 0x42
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Logs) > 0 {
		for _, msg := range m.Logs {
			dAtA[i] = 0x4a
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Process != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.Process.Size()))
		n6, err := m.Process.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.ProcessID) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.ProcessID)))
		i += copy(dAtA[i:], m.ProcessID)
	}
	if len(m.Warnings) > 0 {
		for _, s := range m.Warnings {
			dAtA[i] = 0x62
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *Span2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Span2) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(m.TraceID.Size()))
	n7, err := m.TraceID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	if m.SpanID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(m.SpanID))
	}
	return i, nil
}

func (m *Trace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trace) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Spans) > 0 {
		for _, msg := range m.Spans {
			dAtA[i] = 0xa
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ProcessMap) > 0 {
		for _, msg := range m.ProcessMap {
			dAtA[i] = 0x12
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Warnings) > 0 {
		for _, s := range m.Warnings {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *Trace_ProcessMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trace_ProcessMapping) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ProcessID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.ProcessID)))
		i += copy(dAtA[i:], m.ProcessID)
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(m.Process.Size()))
	n8, err := m.Process.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	return i, nil
}

func (m *Batch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Batch) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Spans) > 0 {
		for _, msg := range m.Spans {
			dAtA[i] = 0xa
			i++
			i = encodeVarintJaeger(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintJaeger(dAtA, i, uint64(m.Process.Size()))
	n9, err := m.Process.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n9
	return i, nil
}

func (m *GetTraceID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTraceID) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintJaeger(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	return i, nil
}

func encodeVarintJaeger(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *TraceID) Size() (n int) {
	var l int
	_ = l
	if m.Low != 0 {
		n += 1 + sovJaeger(uint64(m.Low))
	}
	if m.High != 0 {
		n += 1 + sovJaeger(uint64(m.High))
	}
	return n
}

func (m *KeyValue) Size() (n int) {
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	if m.VType != 0 {
		n += 1 + sovJaeger(uint64(m.VType))
	}
	l = len(m.VStr)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	if m.VBool {
		n += 2
	}
	if m.VInt64 != 0 {
		n += 1 + sovJaeger(uint64(m.VInt64))
	}
	if m.VFloat64 != 0 {
		n += 9
	}
	l = len(m.VBinary)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	return n
}

func (m *Log) Size() (n int) {
	var l int
	_ = l
	l = types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovJaeger(uint64(l))
	if len(m.Fields) > 0 {
		for _, e := range m.Fields {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	return n
}

func (m *SpanRef) Size() (n int) {
	var l int
	_ = l
	l = m.TraceID.Size()
	n += 1 + l + sovJaeger(uint64(l))
	if m.SpanID != 0 {
		n += 1 + sovJaeger(uint64(m.SpanID))
	}
	if m.RefType != 0 {
		n += 1 + sovJaeger(uint64(m.RefType))
	}
	return n
}

func (m *Process) Size() (n int) {
	var l int
	_ = l
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	if len(m.Tags) > 0 {
		for _, e := range m.Tags {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	return n
}

func (m *Span) Size() (n int) {
	var l int
	_ = l
	l = m.TraceID.Size()
	n += 1 + l + sovJaeger(uint64(l))
	if m.SpanID != 0 {
		n += 1 + sovJaeger(uint64(m.SpanID))
	}
	l = len(m.OperationName)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	if len(m.References) > 0 {
		for _, e := range m.References {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	if m.Flags != 0 {
		n += 1 + sovJaeger(uint64(m.Flags))
	}
	l = types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovJaeger(uint64(l))
	l = types.SizeOfStdDuration(m.Duration)
	n += 1 + l + sovJaeger(uint64(l))
	if len(m.Tags) > 0 {
		for _, e := range m.Tags {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	if len(m.Logs) > 0 {
		for _, e := range m.Logs {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	if m.Process != nil {
		l = m.Process.Size()
		n += 1 + l + sovJaeger(uint64(l))
	}
	l = len(m.ProcessID)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	if len(m.Warnings) > 0 {
		for _, s := range m.Warnings {
			l = len(s)
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	return n
}

func (m *Span2) Size() (n int) {
	var l int
	_ = l
	l = m.TraceID.Size()
	n += 1 + l + sovJaeger(uint64(l))
	if m.SpanID != 0 {
		n += 1 + sovJaeger(uint64(m.SpanID))
	}
	return n
}

func (m *Trace) Size() (n int) {
	var l int
	_ = l
	if len(m.Spans) > 0 {
		for _, e := range m.Spans {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	if len(m.ProcessMap) > 0 {
		for _, e := range m.ProcessMap {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	if len(m.Warnings) > 0 {
		for _, s := range m.Warnings {
			l = len(s)
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	return n
}

func (m *Trace_ProcessMapping) Size() (n int) {
	var l int
	_ = l
	l = len(m.ProcessID)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	l = m.Process.Size()
	n += 1 + l + sovJaeger(uint64(l))
	return n
}

func (m *Batch) Size() (n int) {
	var l int
	_ = l
	if len(m.Spans) > 0 {
		for _, e := range m.Spans {
			l = e.Size()
			n += 1 + l + sovJaeger(uint64(l))
		}
	}
	l = m.Process.Size()
	n += 1 + l + sovJaeger(uint64(l))
	return n
}

func (m *GetTraceID) Size() (n int) {
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovJaeger(uint64(l))
	}
	return n
}

func sovJaeger(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozJaeger(x uint64) (n int) {
	return sovJaeger(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TraceID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TraceID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TraceID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Low", wireType)
			}
			m.Low = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Low |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field High", wireType)
			}
			m.High = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.High |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VType", wireType)
			}
			m.VType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VType |= (ValueType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VStr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VStr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VBool", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VBool = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VInt64", wireType)
			}
			m.VInt64 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VInt64 |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field VFloat64", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.VFloat64 = float64(math.Float64frombits(v))
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VBinary", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VBinary = append(m.VBinary[:0], dAtA[iNdEx:postIndex]...)
			if m.VBinary == nil {
				m.VBinary = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Log) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Log: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Log: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fields = append(m.Fields, KeyValue{})
			if err := m.Fields[len(m.Fields)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpanRef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpanRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpanRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TraceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpanID", wireType)
			}
			m.SpanID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SpanID |= (SpanID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefType", wireType)
			}
			m.RefType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RefType |= (SpanRefType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Process) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Process: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Process: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, KeyValue{})
			if err := m.Tags[len(m.Tags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Span) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Span: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Span: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TraceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpanID", wireType)
			}
			m.SpanID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SpanID |= (SpanID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field References", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.References = append(m.References, SpanRef{})
			if err := m.References[len(m.References)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= (Flags(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdDurationUnmarshal(&m.Duration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, KeyValue{})
			if err := m.Tags[len(m.Tags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Logs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Logs = append(m.Logs, Log{})
			if err := m.Logs[len(m.Logs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Process", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Process == nil {
				m.Process = &Process{}
			}
			if err := m.Process.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Warnings", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Warnings = append(m.Warnings, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Span2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Span2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Span2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TraceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpanID", wireType)
			}
			m.SpanID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SpanID |= (SpanID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Trace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spans = append(m.Spans, &Span{})
			if err := m.Spans[len(m.Spans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessMap = append(m.ProcessMap, Trace_ProcessMapping{})
			if err := m.ProcessMap[len(m.ProcessMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Warnings", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Warnings = append(m.Warnings, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Trace_ProcessMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProcessMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProcessMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Process", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Process.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Batch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Batch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Batch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spans = append(m.Spans, &Span{})
			if err := m.Spans[len(m.Spans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Process", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Process.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTraceID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTraceID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTraceID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJaeger
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJaeger(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJaeger
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipJaeger(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowJaeger
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJaeger
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthJaeger
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowJaeger
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipJaeger(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthJaeger = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowJaeger   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("jaeger.proto", fileDescriptorJaeger) }
func init() { golang_proto.RegisterFile("jaeger.proto", fileDescriptorJaeger) }

var fileDescriptorJaeger = []byte{
	// 1070 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x73, 0xdb, 0x44,
	0x14, 0xcf, 0xda, 0x92, 0x3f, 0x9e, 0x3f, 0x6a, 0xb6, 0xd0, 0x11, 0x6e, 0x26, 0x36, 0x62, 0x4a,
	0x4d, 0x20, 0x16, 0x31, 0x4d, 0x0f, 0xe1, 0xc0, 0x44, 0x4d, 0x5d, 0x5c, 0x9c, 0x38, 0xc8, 0x99,
	0xf2, 0x31, 0x9d, 0x09, 0x8a, 0xbd, 0x56, 0x04, 0xb2, 0x56, 0x23, 0x29, 0xce, 0x78, 0x18, 0x2e,
	0xfd, 0x0b, 0xf8, 0xb8, 0xf4, 0x46, 0xf9, 0x4f, 0xb8, 0xd1, 0x23, 0x33, 0xdc, 0x38, 0x14, 0x26,
	0x70, 0xe8, 0x81, 0x3f, 0x82, 0xd9, 0xd5, 0xae, 0x1d, 0xa7, 0x9d, 0x49, 0x39, 0xf4, 0x62, 0xef,
	0x7b, 0xef, 0xf7, 0xde, 0xbe, 0xf7, 0xfb, 0x3d, 0x49, 0x50, 0xfc, 0xca, 0x26, 0x0e, 0x09, 0x9b,
	0x41, 0x48, 0x63, 0x8a, 0x33, 0x89, 0x55, 0xbd, 0xea, 0x50, 0xea, 0x78, 0xc4, 0xe0, 0xde, 0xc3,
	0xe3, 0x91, 0x41, 0xc6, 0x41, 0x3c, 0x4d, 0x40, 0xd5, 0xda, 0xf9, 0x60, 0xec, 0x8e, 0x49, 0x14,
	0xdb, 0xe3, 0x40, 0x00, 0x56, 0xce, 0x03, 0x86, 0xc7, 0xa1, 0x1d, 0xbb, 0xd4, 0x17, 0xf1, 0x65,
	0x11, 0xb7, 0x03, 0xd7, 0xb0, 0x7d, 0x9f, 0xc6, 0x3c, 0x18, 0x89, 0xe8, 0xbb, 0xfc, 0x6f, 0xb0,
	0xe6, 0x10, 0x7f, 0x2d, 0x3a, 0xb1, 0x1d, 0x87, 0x84, 0x06, 0x0d, 0x38, 0xe2, 0x39, 0xe8, 0x35,
	0xc7, 0x8d, 0x8f, 0x8e, 0x0f, 0x9b, 0x03, 0x3a, 0x36, 0x1c, 0xea, 0xd0, 0xf9, 0xa5, 0xcc, 0xe2,
	0x06, 0x3f, 0x25, 0x70, 0x7d, 0x03, 0xb2, 0xfb, 0xa1, 0x3d, 0x20, 0x9d, 0x6d, 0x5c, 0x81, 0xb4,
	0x47, 0x4f, 0x34, 0x54, 0x47, 0x0d, 0xc5, 0x62, 0x47, 0x8c, 0x41, 0x39, 0x72, 0x9d, 0x23, 0x2d,
	0xc5, 0x5d, 0xfc, 0xbc, 0xa9, 0x3c, 0x7c, 0x54, 0x5b, 0xd2, 0x7f, 0x45, 0x90, 0xfb, 0x98, 0x4c,
	0xef, 0xd9, 0xde, 0x31, 0x61, 0x89, 0x5f, 0x93, 0x29, 0x4f, 0xcc, 0x5b, 0xec, 0x88, 0xaf, 0x83,
	0x3a, 0xd9, 0x9f, 0x06, 0x84, 0x67, 0x96, 0x5b, 0xaf, 0x34, 0x05, 0xa9, 0x1c, 0xcf, 0x02, 0x56,
	0x12, 0x67, 0x37, 0x4c, 0xfa, 0x71, 0xa8, 0xa5, 0x79, 0x2e, 0x3f, 0xe3, 0x57, 0x41, 0x9d, 0x98,
	0x94, 0x7a, 0x9a, 0x52, 0x47, 0x8d, 0x9c, 0x95, 0x18, 0xf8, 0x0a, 0x64, 0x26, 0x1d, 0x3f, 0xbe,
	0x79, 0x43, 0x53, 0xeb, 0xa8, 0x91, 0xb6, 0x84, 0x85, 0xab, 0x90, 0x9b, 0xb4, 0x3d, 0x6a, 0xb3,
	0x48, 0xa6, 0x8e, 0x1a, 0xc8, 0x9a, 0xd9, 0x58, 0x83, 0xec, 0xc4, 0x74, 0x7d, 0x3b, 0x9c, 0x6a,
	0xd9, 0x3a, 0x6a, 0x14, 0x2d, 0x69, 0x6e, 0xe6, 0x9e, 0x3e, 0xaa, 0xa1, 0xa7, 0x3f, 0xd7, 0x90,
	0x3e, 0x85, 0x74, 0x97, 0x3a, 0xd8, 0x84, 0xfc, 0x4c, 0x35, 0x3e, 0x49, 0xa1, 0x55, 0x6d, 0x26,
	0xb2, 0x34, 0x25, 0x83, 0xcd, 0x7d, 0x89, 0x30, 0x73, 0x8f, 0x9f, 0xd4, 0x96, 0xbe, 0xfb, 0xb3,
	0x86, 0xac, 0x79, 0x1a, 0x6e, 0x42, 0x66, 0xe4, 0x12, 0x6f, 0x18, 0x69, 0xa9, 0x7a, 0xba, 0x51,
	0x68, 0x55, 0xe4, 0xd8, 0x92, 0x29, 0x53, 0x61, 0x69, 0x96, 0x40, 0xe9, 0xdf, 0x23, 0xc8, 0xf6,
	0x03, 0xdb, 0xb7, 0xc8, 0x08, 0x1b, 0x90, 0x8d, 0x13, 0x1d, 0xc4, 0xed, 0x97, 0x64, 0xb2, 0x90,
	0x47, 0xe4, 0x4a, 0x14, 0x7e, 0x0b, 0x32, 0x51, 0x60, 0xfb, 0x9d, 0xed, 0x44, 0x1d, 0xb3, 0xcc,
	0xc2, 0x7f, 0x3c, 0xa9, 0x65, 0xfa, 0xdc, 0x6b, 0x89, 0x28, 0x5e, 0x83, 0x6c, 0x48, 0x46, 0x5c,
	0x8c, 0x34, 0x17, 0xe3, 0xb2, 0x2c, 0x2c, 0xae, 0xe6, 0x72, 0x48, 0x8c, 0xfe, 0x19, 0x64, 0xf7,
	0x42, 0x3a, 0x20, 0x51, 0x84, 0xdf, 0x80, 0x62, 0x44, 0xc2, 0x89, 0x3b, 0x20, 0x07, 0xbe, 0x3d,
	0x26, 0x42, 0xdf, 0x82, 0xf0, 0xed, 0xda, 0x63, 0x82, 0x57, 0x41, 0x89, 0x6d, 0xe7, 0xa2, 0x79,
	0x39, 0x46, 0xff, 0x49, 0x01, 0x85, 0x5d, 0xf9, 0xf2, 0x46, 0xbd, 0x06, 0x65, 0x1a, 0x90, 0xe4,
	0xc9, 0x4a, 0x5a, 0x4e, 0xd6, 0xaa, 0x34, 0xf3, 0xf2, 0xa6, 0x37, 0x00, 0x42, 0x32, 0x22, 0x21,
	0xf1, 0x07, 0x24, 0xd2, 0x14, 0xde, 0xfa, 0xa5, 0x73, 0xa4, 0x88, 0x16, 0xce, 0x00, 0xf1, 0x9b,
	0xa0, 0x8e, 0x3c, 0x36, 0x2c, 0xdb, 0xbf, 0x92, 0x59, 0x12, 0x4d, 0xa8, 0x6d, 0xe6, 0xb4, 0x92,
	0x18, 0x5b, 0xa3, 0x28, 0xb6, 0xc3, 0x98, 0x6d, 0x0a, 0x5f, 0xc7, 0x17, 0x5e, 0xa3, 0x59, 0x1a,
	0xfe, 0x10, 0x72, 0xf2, 0xfd, 0xc0, 0xd7, 0xb6, 0xd0, 0x7a, 0xfd, 0x99, 0x12, 0xdb, 0x02, 0x90,
	0x54, 0x78, 0xc8, 0x2a, 0xcc, 0x92, 0x66, 0xaa, 0xe4, 0x2e, 0x56, 0x05, 0x5f, 0x03, 0xc5, 0xa3,
	0x4e, 0xa4, 0xe5, 0x39, 0xb6, 0x20, 0xb1, 0x5d, 0xea, 0x48, 0x18, 0x0b, 0xe3, 0xb7, 0x21, 0x1b,
	0x24, 0x6b, 0xa1, 0xc1, 0xa2, 0x66, 0x62, 0x5b, 0x2c, 0x19, 0xc7, 0xcb, 0x90, 0x17, 0xc7, 0xce,
	0xb6, 0x56, 0xe0, 0x02, 0xcc, 0x1d, 0xec, 0x71, 0x3d, 0xb1, 0x43, 0xdf, 0xf5, 0x9d, 0x48, 0x2b,
	0xd6, 0xd3, 0x8d, 0xbc, 0x35, 0xb3, 0xf5, 0x2f, 0x41, 0x65, 0xf4, 0xb7, 0x5e, 0xda, 0x86, 0xe8,
	0xff, 0x22, 0x50, 0x79, 0x09, 0xac, 0x83, 0xca, 0x7c, 0x91, 0x86, 0xf8, 0xe0, 0xc5, 0x05, 0xfd,
	0x93, 0x10, 0x36, 0x01, 0x44, 0xe3, 0x3b, 0x76, 0x20, 0x76, 0x7c, 0x79, 0xa1, 0x13, 0x39, 0xfd,
	0x8e, 0x1d, 0x04, 0xae, 0x2f, 0x29, 0x3b, 0x93, 0xb5, 0x30, 0x6f, 0x7a, 0x71, 0xde, 0xea, 0x01,
	0x94, 0x17, 0xf3, 0x17, 0xb9, 0x43, 0xe7, 0xb9, 0x33, 0xe6, 0x22, 0xa4, 0x9e, 0x2b, 0x82, 0xa4,
	0x45, 0xa0, 0xf4, 0xfb, 0xa0, 0x9a, 0x76, 0x3c, 0x38, 0x7a, 0xa1, 0x69, 0xff, 0x77, 0xf5, 0x65,
	0x80, 0x3b, 0x24, 0x96, 0x5f, 0x8f, 0x32, 0xa4, 0xdc, 0xa1, 0xe8, 0x39, 0xe5, 0x0e, 0x57, 0x6f,
	0x43, 0x7e, 0xf6, 0xb6, 0xc7, 0x00, 0x99, 0xfe, 0xbe, 0xd5, 0xd9, 0xbd, 0x53, 0x59, 0xc2, 0x39,
	0x50, 0xcc, 0x5e, 0xaf, 0x5b, 0x41, 0x38, 0x0f, 0x6a, 0x67, 0x77, 0xff, 0xe6, 0x8d, 0x4a, 0x0a,
	0x17, 0x20, 0xdb, 0xee, 0xf6, 0xb6, 0x98, 0x91, 0x66, 0x68, 0xb3, 0xb3, 0xbb, 0x65, 0x7d, 0x5e,
	0x51, 0x56, 0xd7, 0xa0, 0x70, 0xe6, 0x3d, 0x85, 0x8b, 0x90, 0xbb, 0xf5, 0x51, 0xa7, 0xbb, 0x7d,
	0xd0, 0x6b, 0x57, 0x96, 0x70, 0x05, 0x8a, 0xed, 0x5e, 0xb7, 0xdb, 0xfb, 0xb4, 0x7f, 0xd0, 0xb6,
	0x7a, 0x3b, 0x15, 0xd4, 0x3a, 0x04, 0x7c, 0x8b, 0x7a, 0x1e, 0x19, 0xc4, 0x34, 0xec, 0x27, 0x2f,
	0xaa, 0x7b, 0xeb, 0xb8, 0x0b, 0xf9, 0x3d, 0x1a, 0xc5, 0x7d, 0x3e, 0x67, 0x49, 0x8e, 0xc5, 0xa9,
	0xa9, 0x5e, 0x79, 0xe6, 0xd9, 0xba, 0xcd, 0x3e, 0xed, 0xba, 0xf6, 0xe0, 0xf7, 0x7f, 0x7e, 0x4c,
	0x61, 0xbd, 0xc4, 0xbf, 0xca, 0x93, 0x75, 0x83, 0xb3, 0xb4, 0x89, 0x56, 0x5b, 0xf7, 0xa1, 0xfc,
	0xc9, 0x31, 0x09, 0xa7, 0xf3, 0xfa, 0x77, 0x21, 0x27, 0x99, 0xc0, 0x58, 0x96, 0x9f, 0x73, 0x53,
	0x2d, 0x2d, 0x2c, 0x8d, 0x7e, 0x95, 0x97, 0x7e, 0x0d, 0x5f, 0x96, 0xa5, 0xf9, 0x1a, 0x47, 0xc6,
	0x37, 0xee, 0xf0, 0x5b, 0xf3, 0x01, 0xfa, 0x61, 0xcb, 0xc4, 0x6a, 0x2b, 0xbd, 0xde, 0x7c, 0x6f,
	0x35, 0x85, 0x52, 0xe1, 0x06, 0xc0, 0x5d, 0x9e, 0x5d, 0xdf, 0xda, 0xeb, 0xe0, 0xeb, 0x47, 0x71,
	0x1c, 0x44, 0x9b, 0x86, 0x71, 0xe6, 0x33, 0x9f, 0x14, 0x67, 0x45, 0x5c, 0xdf, 0x11, 0xd6, 0xe3,
	0xd3, 0x15, 0xf4, 0xdb, 0xe9, 0x0a, 0xfa, 0xeb, 0x74, 0x05, 0xfd, 0xf2, 0xf7, 0x0a, 0xfa, 0xe2,
	0x9d, 0x0b, 0x12, 0x8c, 0x31, 0x1d, 0x12, 0xef, 0x03, 0xfe, 0x7b, 0x98, 0xe1, 0x64, 0xbc, 0xff,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x22, 0xa8, 0x66, 0x0d, 0x09, 0x00, 0x00,
}
